image: debian:latest

pages:
  stage: deploy
  script:
  - apt-get update
  - apt-get install -y --no-install-recommends gettext bc
  - cd public
  - ./generate-stats-page.sh > index.html
  artifacts:
    paths:
    - public
  only:
  - master
